CREATE DATABASE IF NOT EXISTS kRobot;

USE kRobot;

CREATE TABLE IF NOT EXISTS commander (
  Ref INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  ItwoC (100) INT,
  Targ INT, 
  Data INT,
  Active BOOL,
  IsRead BOOL,
  AliveAt TIMESTAMP;
  DontAT TIMESTAMP;
  );

CREATE TABLE IF NOT EXISTS DoneIts ( 
  Ref INT NOT NULL PRIMARY KEY AUTO_INCREMENT
  ItwoC (100) INT,
  Targ INT, 
  Data INT,
  IsRead BOOL,
  AliveAt TIMESTAMP,
  DoneAt TIMESTAMP,
  ArchAt TIMESTAMP,
  );
  
CREATE TABLE IF NOT EXISTS RealTimeStatus (
  Ref INT NOT NULL PRIMARY KEY AUTO_INCREMENT
  FMOT_ANGLE_WHEEL_LHS INT,
  FMOT_ANGLE_WHEEL_RHS INT,
  FMOT_SPEED_WHEEL_LHS_FWD INT,  
  FMOT_SPEED_WHEEL_RHS_FWD INT,
  FMOT_SPEED_WHEEL_LHS_REV INT,
  FMOT_SPEED_WHEEL_RHS_REV INT,
  FMOT_TRIM_ANGLE_WHEEL_LHS INT,
  FMOT_TRIM_ANGLE_WHEEL_LHS INT,
  FMOT_WDOG INT,
  FMOT_DUMMY INT,
  
  RMOT_ANGLE_WHEEL_LHS INT,
  RMOT_ANGLE_WHEEL_RHS INT,
  RMOT_SPEED_WHEEL_LHS_FWD INT,  
  RMOT_SPEED_WHEEL_RHS_FWD INT,
  RMOT_SPEED_WHEEL_LHS_REV INT,
  RMOT_SPEED_WHEEL_RHS_REV INT,
  RMOT_TRIM_ANGLE_WHEEL_LHS INT,
  RMOT_TRIM_ANGLE_WHEEL_LHS INT,
  RMOT_WDOG INT,
  RMOT_DUMMY INT,
  
  TRT_MODE INT,
  TRT_ANGLE INT,
  TRT_ELEVATION INT,
  TRT_FIRE INT,
  TRT_ANGLE_STATUS INT,
  TRT_CAL_STATUS INT,
  TRT_SONIC_RANGE INT,
  TRT_TRIM_ELEVATION INT,
  TRT_WDOG INT,
  TRT_DUMMY INT,
  
  SNS_COMMAND INT,
  SNS_DATA_TEXT INT,  
  SNS_GEN_STATUS INT,
  SNS_MSG_ODOMETER_MSB INT, 
  SNS_MSG_ODOMETER_LSB INT, 
  SNS_GPS_LONG_MSB INT, 
  SNS_GPS_LONG_LSB INT,
  SNS_GPS_LAT_MSB INT, 
  SNS_GPS_LAT_LSB INT,
  SNS_GPS_ALTITUDE INT,
  SNS_GPS_TRACK INT,
  SNS_GPS_SATELLITES INT, 
  SNS_GPS_SPEED INT,
  SNS_GPS_YEAR INT,
  SNS_GPS_MONTH INT,
  SNS_GPS_DAY INT, 
  SNS_GPS_HOUR INT, 
  SNS_GPS_MIN INT, 
  SNS_GPS_SECONDS INT, 
  SNS_COMPASS_DIR INT,
  SNS_COMPASS_PITCH INT,
  SNS_COMPASS_ROLL INT,
  SNS_COMPASS_TEMP INT,
  SNS_COMPASS_CALIBRATION INT,
  SNS_11V_LIPO_BUS INT,
  SNS_5V_BUS INT,
  SNS_6V_BUS_1 INT,
  SNS_6V_BUS_2 INT,
  SNS_IR_FRONT_DISTANCE INT,
  SNS_IR REAR_DISTANCE INT, 
  SNS_WDOG INT, 
  SNS_DUMMY INT);


INSERT INTO RealTimeStatus 
VALUES(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0);

